//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tTask
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tTask()
        {
            this.tTrackRecord = new HashSet<tTrackRecord>();
        }
    
        public int idTask { get; set; }
        public int idUser { get; set; }
        public int idTaskState { get; set; }
        public int idSprint { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> lastActivity { get; set; }
        public Nullable<int> estimatedTime { get; set; }
    
        public virtual tSprint tSprint { get; set; }
        public virtual tTaskState tTaskState { get; set; }
        public virtual tUser tUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tTrackRecord> tTrackRecord { get; set; }
    }
}
